#!/usr/bin/env python3
import click

from cli.affine import affine
from cli.caesar import caesar


@click.group()
def cli():
    pass


if __name__ == "__main__":
    cli.add_command(caesar)
    cli.add_command(affine)
    cli()
